export const ST_EDITOR_LOAD_USER_SUCCESS = 'user-status-editor/ST_EDITOR_LOAD_USER_SUCCESS';
export const ST_EDITOR_LOAD_USER_ERROR = 'user-status-editor/ST_EDITOR_LOAD_USER_ERROR';
export const ST_EDITOR_START_LOADING_USERS = 'user-status-editor/ST_EDITOR_START_LOADING_USERS';
export const ST_EDITOR_CHANGE_ACTIVE_EDIT_USER_ID = 'user-status-editor/ST_EDITOR_CHANGE_ACTIVE_EDIT_USER_ID'
export const ST_EDITOR_CHANGE_ACTIVE_EDIT_USER_STATUS = 'user-status-editor/ST_EDITOR_CHANGE_ACTIVE_EDIT_USER_STATUS'

