export const ST_EDITOR_LOAD_USER_SUCCESS = 'user-status-editor/ST_EDITOR_LOAD_USER_SUCCESS';
export const ST_EDITOR_LOAD_USER_ERROR = 'user-status-editor/ST_EDITOR_LOAD_USER_ERROR';
export const ST_EDITOR_START_LOADING_USERS = 'user-status-editor/ST_EDITOR_START_LOADING_USERS';
export const ST_EDITOR_CHANGE_ACTIVE_EDIT_USER_ID = 'user-status-editor/ST_EDITOR_CHANGE_ACTIVE_EDIT_USER_ID'
export const ST_EDITOR_CHANGE_ACTIVE_EDIT_USER_STATUS = 'user-status-editor/ST_EDITOR_CHANGE_ACTIVE_EDIT_USER_STATUS'
export const ST_EDITOR_START_UPDATE_STATUS = 'user-status-editor/ST_EDITOR_START_UPDATE_STATUS'
export const ST_EDITOR_UPDATE_STATUS_SUCCESS = 'user-status-editor/ST_EDITOR_UPDATE_STATUS_SUCCESS'
export const ST_EDITOR_UPDATE_STATUS_ERROR = 'user-status-editor/ST_EDITOR_UPDATE_STATUS_ERROR'
export const ST_EDITOR_CHANGE_SEARCH_TEXT = 'user-status-editor/ST_EDITOR_CHANGE_SEARCH_TEXT'
export const ST_EDITOR_SEARCH_USERS = 'user-status-editor/ST_EDITOR_SEARCH_USERS'

export const EXAM_EDITOR_CHANGE_SELECTED_QS_ID = 'exam-editor/EXAM_EDITOR_CHANGE_SELECTED_QS_ID'
export const EXAM_EDITOR_START_LOADING_QS = 'exam-editor/EXAM_EDITOR_START_LOADING_QS'
export const EXAM_EDITOR_LOAD_QS_SUCCESS = 'exam-editor/EXAM_EDITOR_LOAD_QS_SUCCESS'
export const EXAM_EDITOR_LOAD_QS_ERROR = 'exam-editor/EXAM_EDITOR_LOAD_QS_ERROR'
export const EXAM_EDITOR_CHANGE_ACCESS_TYPE = 'exam-editor/EXAM_EDITOR_CHANGE_ACCESS_TYPE'

