export const CHANGE_SELECTED_QS_ID = 'exam-editor/CHANGE_SELECTED_QS_ID'
export const START_LOADING_QS = 'exam-editor/START_LOADING_QS'
export const LOAD_QS_SUCCESS = 'exam-editor/LOAD_QS_SUCCESS'
export const LOAD_QS_ERROR = 'exam-editor/LOAD_QS_ERROR'
export const CHANGE_ACCESS_TYPE = 'exam-editor/CHANGE_ACCESS_TYPE'
export const START_LOADING_EXAM_DATA = 'exam-editor/START_LOADING_EXAM_DATA'
export const LOAD_EXAM_DATA_SUCCESS = 'exam-editor/LOAD_EXAM_DATA_SUCCESS'
export const CHANGE_EXAM_ID = 'exam-editor/CHANGE_EXAM_ID'
